### ISSUE TITLE
iOS 12.2

### ISSUE THREAD

**Issue by roberkane212** [bschlenk/homebridge-roku#65] opened 2019-01-31 21:43 UTC
anyway we can get this plugin working with the new update. Ive seen it done with other plugins

**Comment by bschlenk** [comment] 2019-01-31 21:47
There’s a pull request that updates it to use the new tv services: https://github.com/bschlenk/homebridge-roku/pull/63

I’ll look into merging it in when I have some free time.

**Comment by roberkane212** [comment] 2019-01-31 22:09
ive seen it, was wondering if you had a config on this. i don't see one in the post. i have an rpi

**Comment by bschlenk** [comment] 2019-02-04 05:35
Do you mean a homebridge config? If you pull down @zwaldowski's branch and run `./bin/setup`, it will print out a config that works with the changes.

**Comment by roberkane212** [comment] 2019-02-04 13:06
Can you tell me how to pull down the branch? I don’t see it, sorry I’ve never done it before

**Comment by bschlenk** [comment] 2019-02-12 04:30
I just released v3.0.0-alpha.0 with the updates from https://github.com/bschlenk/homebridge-roku/pull/63. You can install it with `npm install -g homebridge-roku@next`.

Config files will need to be updated. `appMap` is no longer used and has been replaced with `inputs`, which is an array. Running the setup script will print out the config with the `inputs` field. I haven't tested it yet with `--merge` so use that at your own risk. I would recommend manually adding the `inputs` field and keeping the `appMap` field. That way you can switch back to v2 easily if you want.

v3 will only work on iOS 12.2 and above. You can learn how to install the beta at [beta.apple.com](https://beta.apple.com/sp/betaprogram/).

**Comment by roberkane212** [comment] 2019-02-12 04:49
can you let me know how to run set up script please, im sorry i know these question must seem dumb to you

**Comment by roberkane212** [comment] 2019-02-12 05:11
go it to work, but after a few seconds it goes to no response

**Comment by roberkane212** [comment] 2019-02-12 05:48
Thanks you soooooo much!!!!! I’m working on getting it working, but I’ve got the change to 12.2 just got to get it to respond

**Comment by ckeone** [comment] 2019-02-12 16:54
> I just released v3.0.0-alpha.0 with the updates from #63. You can install it with `npm install -g homebridge-roku@next`.
> 
> Config files will need to be updated. `appMap` is no longer used and has been replaced with `inputs`, which is an array. Running the setup script will print out the config with the `inputs` field. I haven't tested it yet with `--merge` so use that at your own risk. I would recommend manually adding the `inputs` field and keeping the `appMap` field. That way you can switch back to v2 easily if you want.
> 
> v3 will only work on iOS 12.2 and above. You can learn how to install the beta at [beta.apple.com](https://beta.apple.com/sp/betaprogram/).

Is the setup script in at alpha already updated to provide a config printout using `inputs`? I'm still only seeing `appMap`?

**Comment by rasod** [comment] 2019-02-13 00:43
There is a tiny syntax error in the setup script preventing it from running. Line 26 has a extra comma.

https://github.com/bschlenk/homebridge-roku/blob/1c14e111a5cf0359929a666ab200ae6269bb6dcc/src/setup.js#L25-L27

**Comment by Mxdanger** [comment] 2019-02-13 01:23
I’ve got it to work by first uninstalling the roku plugin and then installing the developer build using `sudo npm install --unsafe-perm -g homebridge-roku@next`. It also seems the inputs will not work if you keep the `appMap` field so you could delete the field or just run `homebrige-roku-config --merge` as I had no problems with it.

**Comment by zwaldowski** [comment] 2019-02-13 01:26
@rasod What are you seeing and what version of Node are you running? It runs for me.

**Comment by rasod** [comment] 2019-02-13 01:37
@zwaldowski 

```
/usr/local/lib/node_modules/homebridge-roku/src/setup.js:27
        )
        ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-roku/bin/setup:9:5)
```

I am on a older version of node 6.11

**Comment by bschlenk** [comment] 2019-02-13 14:52
Ah, yeah I forgot older node versions don't support trailing commas. I'll update it.

**Comment by bschlenk** [comment] 2019-02-13 15:24
Published homebridge-roku@3.0.0-alpha.1 with the trailing commas removed

**Comment by roberkane212** [comment] 2019-02-13 16:52
How do I run this new homebridge-roku?sudo npm install -g homebridge-roku@3.0.0-alpha. 1 ?

**Comment by krazyflipj** [comment] 2019-02-13 18:56
@roberkane212  should be `npm install -g homebridge-roku@next`

**Comment by krazyflipj** [comment] 2019-02-14 06:12
Roku remote isn't an option under Apple TV. Anyone else experiencing this?

**Comment by Mxdanger** [comment] 2019-02-14 18:38
I got it working good. ![Image](https://i.imgur.com/qj4zVtM.jpg?raw=true)

> Roku remote isn't an option under Apple TV. Anyone else experiencing this?

@krazyflipj Have you correctly installed it? See [my comment](https://github.com/bschlenk/homebridge-roku/issues/65#issuecomment-463015180) on how I got it working.

**Comment by krazyflipj** [comment] 2019-02-15 05:33
tried all that. Still doesn't show. Everything else works fine just missing the remote

**Comment by roberkane212** [comment] 2019-02-15 20:43
any advice on this error?

/usr/bin/homebridge-roku-config -> /usr/lib/node_modules/homebridge-roku/bin/setup

> curve25519-n@1.4.0 install /usr/lib/node_modules/homebridge-roku/node_modules/curve25519-n
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack at PythonFinder. (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-roku/node_modules/curve25519-n
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-02-15T20_36_03_434Z-debug.

**Comment by Mxdanger** [comment] 2019-02-15 21:52
@roberkane212 mind telling us what you did to cause those errors to appear?

**Comment by roberkane212** [comment] 2019-02-15 23:04
I’m not sure

**Comment by Mxdanger** [comment] 2019-02-15 23:26
…so you’re telling me you had no problems installing and no problems when you run homebridge and those errors just randomly appeared in the shell? Could you please give more context before you ask a question.

**Comment by roberkane212** [comment] 2019-02-15 23:43
No sorry I can run homebridge this comes up when I try to install new roku plugin. As long as I don’t add input in config homebridge runs fine

**Comment by dVIAN13** [comment] 2019-02-17 19:58
> 
> _UPDATE_ Seems like one remote per homebridge hub

I can confirm the restriction of only allowing one TV in the control center 'Remote App'.. hopefully Apple allows more than one in a future beta.

**Comment by Mxdanger** [comment] 2019-02-18 03:35
I believe it could also be one TV per bridge. For people who own multiple Apple TVs can you confirm that you can press the drop down in the control center remote and select other TVs to remote control?

**Comment by dVIAN13** [comment] 2019-02-18 04:28
That is what I was saying... the Apple TV remote app in control center DOES support multiple AppleTV boxes, currently. So only supporting one TV may be a limitation of apple’s AirPlay for TV protocol.

**Comment by zwaldowski** [comment] 2019-02-20 03:55
Fair warning, beta 3 seems to change around and break some functionality, including the volume rocker and some of the remote buttons. Everything over HomeKit seems to be working and they appear to be UI bugs.

**Comment by mxdanger** [comment] 2019-02-24 19:35
Yep you’re right Beta 3 broke the controller. The back button doesn’t work and “i” acts as the home button.
![iOS 12.2 Beta 3 control center remote](https://i.imgur.com/a05VRja_d.jpg?raw=true)
![iOS 12.2 Beta 3 control center remote while selecting the drop down](
https://i.imgur.com/ozTLRmd_d.jpg?raw=true) Here’s the [Imgur Album](https://imgur.com/a/7rnm5Q1).

**Comment by zwaldowski** [comment] 2019-02-25 23:20
- Opened "<rdar://problem/48225345> Remote keys for HAP TV volume control don't do anything" with Apple, marked as dupe of <rdar://problem/48099853>.
- Opened "<rdar://problem/48224976> Buttons on virtual remote start to lag after Apple TV goes to sleep" with Apple, was asked for additional logs.
- Opened "<rdar://problem/48225246 > Remote keys for HAP TV 'Back' doesn't do anything" with Apple, haven't heard back so far.

**Comment by zwaldowski** [comment] 2019-03-04 23:43
Very happy to report that the remote-related issues are fixed in Beta 4:

- Volume rocker works again.
- "BACK" button works again as Roku's Back button.
- "ℹ️" button works again as Roku's Star/Options button.

**Comment by nicoduj** [comment] 2019-03-12 19:40
Hi @zwaldowski ,
I am working on the plugin for harmony which exposes also the tv service, but currently I can’t figure out how some functions works ( see there : https://github.com/KhaosT/HAP-NodeJS/issues/653 ) Did you have any luck with them by any chance ?

**Comment by roberkane212** [comment] 2019-03-19 08:14
Just an FYI beta 6 might take away the option for tv’s in remote

**Comment by nicoduj** [comment] 2019-03-19 12:26
@roberkane212 why are you saying that ? I have tested yesterday with my haronybolugin and still seems ok

**Comment by roberkane212** [comment] 2019-03-19 12:32
@nicoduj because when I first updated it was gone. So just warning others it might happen

**Comment by senseotech** [comment] 2019-03-19 14:34
Upgraded to beta 6 here and can confirm that TV still shows in the Control Center remote, albeit still just one of the 2 configured, seemingly randomly switching which is visible, so either Apple is only supporting a single TV in there for now, or they still have a bug that prevents others from showing.

**Comment by nicoduj** [comment] 2019-03-19 16:52
From my knowledge it only supports one tv accessory per homebridge instance. Discovery of tv accessory seems to rely on bonjour service so it supports only one per homebridge . But having multiple homebridge instance with each one a tv accessory seems to work

**Comment by senseotech** [comment] 2019-03-25 14:45
> From my knowledge it only supports one tv accessory per homebridge instance. Discovery of tv accessory seems to rely on bonjour service so it supports only one per homebridge . But having multiple homebridge instance with each one a tv accessory seems to work

Hmm, so either get multiple homebridge instances running on one machine and bind them to different interfaces (in my case, its a VM, so adding an extra interface or two is not terrible), or just create a new VM for each.

**Comment by nicoduj** [comment] 2019-03-25 14:57
Maybe just try 2 instances from the same machine at first , but not sur it will work .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by senseotech** [comment] 2019-03-25 15:57
> Maybe just try 2 instances from the same machine at first , but not sur it will work .
> 
> Sent with [GitHawk](http://githawk.com)

Got a second instance running (as a service with its own config-ui-x even) easily enough, then remembered I can't actually add the new bridge to the Home App over a VPN, so I'll have to wait until I get home from work to see if that's enough to get two TVs showing up.  If it is, I'll then need to duplicate the instance again: 2 for the Roku TVs and this plugin, then a third for your wonderful Harmony plugin on a not-so-smart TV setup.

**Comment by nicoduj** [comment] 2019-03-25 16:05
Let me know , i am curious about this :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by senseotech** [comment] 2019-03-25 22:14
> Let me know , i am curious about this :)
> 
> Sent with [GitHawk](http://githawk.com)

Second instance on the same machine was enough to get it working; the bottom 2 listings in this image are both Roku TVs using this plugin, one configured on each HomeBridge instance.  There should be a third AppleTV listed that's not; I'm hoping that's just the unit in a bad state and not some weird 4-device display limit.  I'm updating everyone to 12.2 (iOS and tvOS) and hoping that the reboot will shake the other ATV loose.
<img width="311" alt="20190325_221037926_iOS" src="https://user-images.githubusercontent.com/48096504/54957659-c6425480-4f29-11e9-8127-c8f9b5ed56ab.png">

**Comment by nicoduj** [comment] 2019-03-25 22:20
Great ! Hope also it is not limited to 4 ;)

**Comment by roberkane212** [comment] 2019-03-26 00:12
@senseotech how did you run more than one on same machine? Are you using RPi?

**Comment by nicoduj** [comment] 2019-03-26 06:36
This could now be overcome ! : thanks to @KhaosT https://github.com/nfarina/homebridge/issues/2184

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by senseotech** [comment] 2019-03-26 19:23
> Great ! Hope also it is not limited to 4 ;)

Its not; After getting my AppleTV 4k to finally update and reboot, I can now see 3 ATVs and 2 Roku TVs in the Control Center Remote dropdown!

> @senseotech how did you run more than one on same machine? Are you using RPi?

I have an Ubuntu server virtual machine that houses homebridge.  I followed this great tutorial to run homebridge as a service:

[https://timleland.com/setup-homebridge-to-start-on-bootup/](url)

And just ran through it a second time, creating a new folder, user, service definition, etc.  I also had to change the configuration code, port, and username/MAC address in the confg.json.  With all that done, I have two instance running on the same machine, sharing plugin installs, but using their own configurations.

**Comment by nicoduj** [comment] 2019-03-26 20:51
Ok so I managed to make this works with one homebridge instance for my plugin . see : https://twitter.com/dujnic/status/1110644949027041282 and https://www.npmjs.com/package/homebridge-harmony/v/1.0.0-beta8

**Comment by roberkane212** [comment] 2019-03-27 03:02
@nicoduj how did you get this working? I don’t see anything when I attempt to add accessory

**Comment by nicoduj** [comment] 2019-03-27 05:56
@roberkane212  hi, first you have to use homebridge latest 0.0.48 and latest beta of my plugin (1.0.0beta8)
Then, you also need to have only my plugin for the moment, since if Roku or other already published a tv device then the first one in your harmony config won’t be visible . I will modify that since I didn’t consider in my implementation that others could expose tv devices :) 

So once your are in this conditions, just add 2 subplatforms with each one a hub exposed as tv device . The first one will be added with the bridge, the second will have to be added manually (you will see a log in homebridge start process). Once again I will make possible to publish even the first one this way if others plugin are already publishing one, maybe tonight :)

Last, if you have some port blocking / filtering on your homebridge, you have to use the ports config of homebridge to define the range that will be used for each tv device (which is dynamic bu default). See config.sample in homebridge github repository .



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by roberkane212** [comment] 2019-03-28 16:18
@nicoduj now i am getting this error

[2019-3-28 16:16:38] [28" Sanyo TV] INFO - Loading activities...
[2019-3-28 16:16:38] [28" Sanyo TV] Error - Error retrieving info from hub : Error: getaddrinfo ENOTFOUND undefined undefined:8088-(4/3)
Unhandled rejection Error - Harmony HUB at undefined is not available - can't start plugin

**Comment by roberkane212** [comment] 2019-03-28 16:22
my config is

"platform": "HarmonyHubWebSocket",
			"name": "TV",
			"subPlatform": [{
      "name": "Harmony Hub",
			"hubIP": "192.168.0.5",
			"TVPlatformMode": true,
			"mainActivity": " The TV"
			}]

**Comment by nicoduj** [comment] 2019-03-28 16:39
@roberkane212 please post on my github don’t want to make too much « pollution » there 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by roberkane212** [comment] 2019-03-28 17:22
@nicoduj sorry I was rushing to get it. My apologies

**Comment by roberkane212** [comment] 2019-03-28 17:34
@nicoduj I have posted there thanks for all your help

**Comment by natcl** [comment] 2019-04-11 02:13
I get a strange error:

```
2|homebridge  | [2019-4-10 22:10:42] [Roku] Initializing Roku accessory...
2|homebridge  | TypeError: Cannot read property 'REWIND' of undefined
2|homebridge  |     at new RokuAccessory (/usr/lib/node_modules/homebridge-roku/src/homebridge-roku.js:38:33)
2|homebridge  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:296:29)
2|homebridge  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
2|homebridge  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
2|homebridge  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
2|homebridge  |     at Module._compile (module.js:653:30)
2|homebridge  |     at Object.Module._extensions..js (module.js:664:10)
2|homebridge  |     at Module.load (module.js:566:32)
2|homebridge  |     at tryModuleLoad (module.js:506:12)
2|homebridge  |     at Function.Module._load (module.js:498:3)
2|homebridge  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
2|homebridge  |     at Module._compile (module.js:653:30)
2|homebridge  |     at Object.Module._extensions..js (module.js:664:10)
2|homebridge  |     at Module.load (module.js:566:32)
2|homebridge  |     at tryModuleLoad (module.js:506:12)
2|homebridge  |     at Function.Module._load (module.js:498:3)
2|homebridge  |     at Function.Module.runMain (module.js:694:10)
2|homebridge  |     at startup (bootstrap_node.js:204:16)
2|homebridge  |     at bootstrap_node.js:625:3
```
Any ideas ?
Thanks !

**Comment by Garulf** [comment] 2019-06-11 09:22
> I get a strange error:
> 
> ```
> 2|homebridge  | [2019-4-10 22:10:42] [Roku] Initializing Roku accessory...
> 2|homebridge  | TypeError: Cannot read property 'REWIND' of undefined
> 2|homebridge  |     at new RokuAccessory (/usr/lib/node_modules/homebridge-roku/src/homebridge-roku.js:38:33)
> 2|homebridge  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:296:29)
> 2|homebridge  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
> 2|homebridge  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
> 2|homebridge  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
> 2|homebridge  |     at Module._compile (module.js:653:30)
> 2|homebridge  |     at Object.Module._extensions..js (module.js:664:10)
> 2|homebridge  |     at Module.load (module.js:566:32)
> 2|homebridge  |     at tryModuleLoad (module.js:506:12)
> 2|homebridge  |     at Function.Module._load (module.js:498:3)
> 2|homebridge  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:75:21)
> 2|homebridge  |     at Module._compile (module.js:653:30)
> 2|homebridge  |     at Object.Module._extensions..js (module.js:664:10)
> 2|homebridge  |     at Module.load (module.js:566:32)
> 2|homebridge  |     at tryModuleLoad (module.js:506:12)
> 2|homebridge  |     at Function.Module._load (module.js:498:3)
> 2|homebridge  |     at Function.Module.runMain (module.js:694:10)
> 2|homebridge  |     at startup (bootstrap_node.js:204:16)
> 2|homebridge  |     at bootstrap_node.js:625:3
> ```
> 
> Any ideas ?
> Thanks !

Upgrading my Homebridge installation fixed this error for me. Hope that helps.

**Comment by natcl** [comment] 2019-08-05 01:20
Still have the error with rewind with the latest homebridge :/ what version of nodejs are you using ?

**Comment by sachangregory** [comment] 2019-08-05 21:41
![103700D2-0EE7-43B3-92D3-8453B8C82B42](https://user-images.githubusercontent.com/19377918/62496853-3c907680-b7a8-11e9-87d5-e28216eae0a0.png)

How do I fix this error?

**Comment by natcl** [comment] 2019-08-05 22:52
Update on my issue, I had 2 copies of homebridge running and wasn't running the latest one, works now.

**Comment by byardley97** [comment] 2019-09-05 22:19
TypeError: Cannot read property 'map' of undefined
    at RokuAccessory.setupInputs (/usr/local/lib/node_modules/homebridge-roku/src/homebridge-roku.js:221:32)
    at RokuAccessory.setup (/usr/local/lib/node_modules/homebridge-roku/src/homebridge-roku.js:61:32)
    at new RokuAccessory (/usr/local/lib/node_modules/homebridge-roku/src/homebridge-roku.js:53:10)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)


receiving this error

**Comment by bschlenk** [comment] 2020-06-01 05:41
[v3.0.0](https://github.com/bschlenk/homebridge-roku/blob/master/CHANGELOG.md#300-2020-06-01) is officially released

**Closed by bschlenk** 2020-06-01 05:41 UTC
