### ISSUE TITLE
Power on the TV

### ISSUE THREAD

**Issue by jminardi** [bschlenk/homebridge-roku#4] opened 2017-10-20 16:51 UTC
I know the documentation says this isn't possible, but my Roku iOS app can power the TV on so there must be some way to do it without an IR blaster. Would it be possible for homebridge-roku to use the same method that the app uses?

**Comment by bschlenk** [comment] 2017-10-20 17:19
The app uses the roku's rest endpoint, which this uses as well. It can turn the TV on if it was only recently powered off. The problem is that the TV turns off its wifi radio after some amount of idle time which prevents the command from being recieved.  

The on/off command is implemented in homebridge-roku, so if it works with your app then it should also work with Siri.

**Comment by jminardi** [comment] 2017-10-20 17:44
Ah OK thanks for the info. I never tried turning on after a long wait so I guess I would have the same issues as you.

**Comment by jminardi** [comment] 2017-10-21 18:42
Ok so I just tried turning on my TV after a longer amount of time through the app and I was able to, but the prompt was different:

![img_0401](https://user-images.githubusercontent.com/1882746/31854886-028bd688-b66e-11e7-83f9-dd7ed920db46.PNG)

Do you know if `homebridge-roku` can wake from "Eco Mode"

**Comment by bschlenk** [comment] 2017-10-21 19:26
Interesting, I've never seen this eco-mode prompt. I just tried and my app couldn't even find my TV (turned off last night, ~10 hours ago). 

What model tv do you have? Mine is
Roku TV 5115X
TCL model 55FS3700

I looked for an eco mode setting but the closest thing I could find is auto power savings, which I have set to turn off after 4 hours. Doesn't seem related to eco mode.

**Comment by jminardi** [comment] 2017-10-21 23:27
I have:

Roku TV 7105X
TCL model 55S405

Is there any way for me to enumerate valid REST endpoints using the API somehow? I could look to see if I have a specific endpoint for waking from eco mode

**Comment by bschlenk** [comment] 2017-10-24 16:05
Are you able to run the config generator of the bin folder? It’ll spit out an info section that is a direct dump of the info endpoint of your Roku tv. On mine there are a bunch of “supportsFeatureX” booleans. Maybe there’s one for eco mode?

**Comment by jminardi** [comment] 2017-11-06 04:38
I got the following error when I tried to run the config generator:

```bash
pi@raspberrypi:/usr/lib/node_modules/homebridge-roku/bin $ ./homebridge-roku-config 
TypeError: app.get is not a function
    at apps.forEach.app (/usr/lib/node_modules/homebridge-roku/bin/homebridge-roku-config:13:18)
    at Array.forEach (native)
    at device.apps.then.apps (/usr/lib/node_modules/homebridge-roku/bin/homebridge-roku-config:12:17)
```

My `npm` version is 3.10.10
My `node` version is v6.10.2

**Comment by jminardi** [comment] 2017-11-06 04:47
Ok, not it is no longer finding my Roku TV. I tried bumping the timeout up to 20 seconds. 

```
Error: Could not find any Roku devices. Time spent: 20 seconds
    at Timeout.setTimeout (/usr/lib/node_modules/homebridge-roku/node_modules/nodeku/lib/discovery.js:25:21)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by Jefronty** [comment] 2017-12-14 18:36
My RokuTV can be powered on by WOL.  If you add the TV's mac address to the configuration you could use WOL to power on a Roku TV if it has been off long enough to not accept the http request.

**Comment by bschlenk** [comment] 2017-12-15 05:29
I'm not sure if my roku tv supports WOL. I just tried with the library you mentioned and nothing happens. Can you test on yours? You can submit a pull request if you get it to work. The mac address gets stored in the config under info.wifi-mac

**Comment by Jefronty** [comment] 2017-12-15 13:31
Does your TV have ethernet?  I don't know if any wifi connection supports WOL.

**Comment by bschlenk** [comment] 2017-12-15 16:12
That explains why it wasn't working. No, I think only the 4K versions have Ethernet. Is Ethernet Mac address part of the info object? If not then it might need to be manually added.

**Comment by Jefronty** [comment] 2017-12-15 16:36
yes it is  
```
        <supports-ethernet>true</supports-ethernet>
        <wifi-mac>00:11:22:33:aa:bb</wifi-mac>
        <ethernet-mac>00:11:22:33:aa:bc</ethernet-mac>
        <network-type>ethernet</network-type>
```

**Comment by jminardi** [comment] 2017-12-15 20:17
I am able to wake my TV over wifi. I do have the 4K version.

**Comment by Jefronty** [comment] 2017-12-15 20:49
Good to know @jminardi that means if implemented it should check the `network-type` value to determine which mac address to attempt to wake

**Comment by bschlenk** [comment] 2018-06-20 06:08
Here is the state of things:

* Newer TVs which support eco mode can be powered on with the current implementation at any time.
* TVs which support wake on LAN can be woken with a magic packet. See [wake_on_lan].(https://github.com/agnat/node_wake_on_lan)
  * A TV with the flag "supports-wake-on-wlan" can be woken over wifi and should use the wifi-mac address.
  * A TV with the flag "supports-wake-on-lan" can be woken over ethernet and I assume there would be a corresponding mac address field in the config.
      * Only some TVs have an ethernet port
  * The correct method to use depends on the value of "network-type", which would be "wifi" or probably "ethernet".
* Some TVs support CEC - not sure if there is a flag for this. See [this homebridge accessory](https://github.com/jbree/homebridge-cec-accessory).
* Older TVs would need some kind of IR blaster because none of the above strategies are supported.

My TV doesn't support any of these. I can turn it on from the rest endpoint if the TV was recently turned off, but that's it.

I don't feel comfortable trying to implement wake on lan or CEC without a TV that I can test it on. If someone with a newer TV model wants to tackle it, feel free to submit a pull request. The change would be made around [here](https://github.com/bschlenk/homebridge-roku/blob/master/src/homebridge-roku.js#L57).

I opened a [new issue](https://github.com/bschlenk/homebridge-roku/issues/9) to act as a collection of configs from various devices to try and figure out all the possible values. It would be helpful to see the configs of a range of devices to help make power on work as best as possible.

**Comment by Jefronty** [comment] 2018-09-17 20:29
I've added my TV's device info to the other thread, but I want to mention that my TV has both ethernet and WiFi, but I use ethernet.  It has the flag `supports-wake-on-wlan` = true, and there is no `supports-wake-on-lan` flag, but I can verify that it does support WOL over ethernet.

**Comment by bschlenk** [comment] 2019-02-04 05:55
@Jefronty I see you started adding [wol support](https://github.com/Jefronty/homebridge-roku/commits/master), did you end up getting that to work? Feel free to open a pull request with your changes.

**Comment by Jefronty** [comment] 2019-04-08 16:02
I just recently actually added roku to my homebridge setup.  On my fork I added a dependency for [wake_on_lan](https://github.com/agnat/node_wake_on_lan) and edited setupSwitch in src/homebridge-roku.js but it did not work.  When I replaced the packages.json and src/homebridge-roku.js with my edited code homebridge failed to start  
I'd appreciate any feed back/suggestions on getting it to work.  Now that I've actually added my TV to homebridge I can test it.

**Comment by bschlenk** [comment] 2020-06-01 02:37
This issue is fairly old, and with eco mode a tv is always able to be turned on. I'm closing for now, if you feel like adding wake on lan support would still be useful, feel free to reopen.

**Closed by bschlenk** 2020-06-01 02:37 UTC

**Comment by Haglerd** [comment] 2020-06-01 03:12
@bschlenk  Sorry I know you just closed this, but  could you not use something like the roku Siri shortcut within the plugin to turn it on and off? I have No idea how the plugins are coded and their capabilities, but just thought I would mention it. 

![16FCF3F6-89CC-4654-B120-109729B3FA1F](https://user-images.githubusercontent.com/13811563/83372759-dce50680-a38b-11ea-85fb-534fccd815c8.png)

[Siri Roku Shortcuts ](https://www.google.com/amp/s/techwiser.com/roku-siri-shortcuts/amp/)

**Comment by bschlenk** [comment] 2020-06-01 06:13
@Haglerd yes! That’s what the plugin does essentially. But that requires that your tv has an eco mode setting that keeps the tv on so it can still listen for commands. Older rokus don’t have this feature, but may support wake on lan instead. Newer roku TVs will power on just fine with the current plugin.

**Comment by bachphi** [comment] 2025-04-22 23:07
> My RokuTV can be powered on by WOL. If you add the TV's mac address to the configuration you could use WOL to power on a Roku TV if it has been off long enough to not accept the http request. NPM package [wake_on_lan](https://github.com/agnat/node_wake_on_lan) In the python roku controller I wrote I set the http request to timeout after two seconds. If it does for power it attempts WOL.

I've seen mixed reviews about Wake-on-LAN over Wi-Fi actually working. My TV has Fast TV Start enabled, and the supports-wake-on-wlan=true flag is set. I've tried WOL using JavaScript, Python, PowerShell, and .NET, but no luck so far. Can you confirm if it's still working for you?

**Comment by Jefronty** [comment] 2025-04-24 17:47
> > My RokuTV can be powered on by WOL. If you add the TV's mac address to the configuration you could use WOL to power on a Roku TV if it has been off long enough to not accept the http request. NPM package [wake_on_lan](https://github.com/agnat/node_wake_on_lan) In the python roku controller I wrote I set the http request to timeout after two seconds. If it does for power it attempts WOL.
> 
> I've seen mixed reviews about Wake-on-LAN over Wi-Fi actually working. My TV has Fast TV Start enabled, and the supports-wake-on-wlan=true flag is set. I've tried WOL using JavaScript, Python, PowerShell, and .NET, but no luck so far. Can you confirm if it's still working for you?

My setup is still working.  I first attempt to power on via the API and if that times out I send a WOL packet.  But my TV is connected via Ethernet, not WI-Fi.  I have heard of some people successfully using WOL over Wi-Fi, but have also heard of it not working for others.

**Comment by bachphi** [comment] 2025-05-01 17:11
> I am able to wake my TV over wifi. I do have the 4K version.

@jminardi, Can you confirm if you can still WOL over wifi with the current RokuOS  v.14.5.4 ???
